apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: eureka
  name: eureka
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: eureka
    spec:
      containers:
      - image: my-registry:5000/eureka-server-img
        name: eureka
        resources: {}
        ports:
        - containerPort: 8761
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
status: {}

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-stack-sentence.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: subject
  name: subject
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: subject
    spec:
      containers:
      - args:
        - -jar
        - -Dspring.profiles.active=subject
        - word.jar
        image: my-registry:5000/word-img
        name: subject
        resources: {}
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
status: {}

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-stack-sentence.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: verb
  name: verb
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: verb
    spec:
      containers:
      - args:
        - -jar
        - -Dspring.profiles.active=verb
        - word.jar
        image: my-registry:5000/word-img
        name: verb
        resources: {}
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
status: {}

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-stack-sentence.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: object
  name: object
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: object
    spec:
      containers:
      - args:
        - -jar
        - -Dspring.profiles.active=object
        - word.jar
        image: my-registry:5000/word-img
        name: object
        resources: {}
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
status: {}

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-stack-sentence.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: sentence
  name: sentence
spec:
  replicas: 2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: sentence
    spec:
      containers:
      - image: my-registry:5000/sentence-img
        name: sentence
        resources: {}
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
status: {}

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-stack-sentence.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: zuul
  name: zuul
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: zuul
    spec:
      containers:
      - image: my-registry:5000/sentence-zuul-img
        name: zuul
        resources: {}
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: zuul-node-port
  labels:
    name: zuul-node-port
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      name: zuul-node-port
  externalIPs:
    - 10.11.1.71
    - 10.11.1.72
    - 10.11.1.73
  selector:
    io.kompose.service: zuul